packages:
  - "packages/*"

catalog:
  # Shared dependencies across multiple packages
  "@antfu/eslint-config": ^6.7.3
  "@faker-js/faker": ^10.2.0
  "@iconify-json/lucide": ^1.2.83
  "@iconify-json/mdi": ^1.2.3
  "@stylistic/stylelint-plugin": ^4.0.0
  "@tailwindcss/postcss": ^4.1.18
  "@types/node": ^24.0.1
  "@types/prismjs": ^1.26.4
  "@vitejs/plugin-vue": ^6.0.3
  "@vitest/coverage-v8": ^4.0.16
  "@vue/test-utils": ^2.4.6
  "@vueuse/core": ^14.1.0
  autoprefixer: ^10.4.23
  bumpp: ^10.3.2
  cross-env: ^10.1.0
  eslint: ^9.12.0
  jsdom: ^27.4.0
  minimist: ^1.2.8
  postcss: ^8.5.6
  postcss-html: ^1.7.0
  prettier: ^3.3.3
  prettier-plugin-tailwindcss: ^0.7.2
  prismjs: ^1.29.0
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^7.4.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^39.0.1
  stylelint-order: ^7.0.1
  tailwindcss: ^4.1.18
  typescript: ^5.6.3
  unplugin-icons: ^22.5.0
  unplugin-vue-components: ^30.0.0
  vite: npm:rolldown-vite@latest
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-docgen-web-types: ^0.1.8
  vue-prism-editor: 2.0.0-alpha.2
  vue-router: ^4.6.4
  vue-tsc: ^3.2.2
