/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CircleProgress: typeof import('./src/components/CircleProgress.vue')['default']
    DemoCode: typeof import('./src/components/DemoCode.vue')['default']
    DemoGroup: typeof import('./src/components/DemoGroup.vue')['default']
    DemoSingle: typeof import('./src/components/DemoSingle.vue')['default']
    DemoTransition: typeof import('./src/components/DemoTransition.vue')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiNpm: typeof import('~icons/mdi/npm')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavLogo: typeof import('./src/components/NavLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionDuration: typeof import('./src/components/TransitionDuration.vue')['default']
    TransitionsOptions: typeof import('./src/components/TransitionsOptions.vue')['default']
  }
}
