/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearControls: typeof import('./src/components/appear/AppearControls.vue')['default']
    AppearNav: typeof import('./src/components/appear/AppearNav.vue')['default']
    BetweenControls: typeof import('./src/components/between/BetweenControls.vue')['default']
    BetweenNav: typeof import('./src/components/between/BetweenNav.vue')['default']
    CircleProgress: typeof import('./src/components/CircleProgress.vue')['default']
    DemoCode: typeof import('./src/components/DemoCode.vue')['default']
    ILucideMoon: typeof import('~icons/lucide/moon')['default']
    ILucideSun: typeof import('~icons/lucide/sun')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiNpm: typeof import('~icons/mdi/npm')['default']
    ListControls: typeof import('./src/components/list/ListControls.vue')['default']
    ListNav: typeof import('./src/components/list/ListNav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavLogo: typeof import('./src/components/NavLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionDuration: typeof import('./src/components/TransitionDuration.vue')['default']
    TransitionsOptions: typeof import('./src/components/TransitionsOptions.vue')['default']
  }
}
